name: Docker CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: actions/setup-python@v3
      with:
        python-version: 3.12

    - name: Build Docker image
      run: docker build -t my-django-app .

    - name: Run Docker container
      run: docker run -d -p 8000:8000 --name my-django-container my-django-app

    - name: Wait for Django to start
      run: |
        while ! curl -s http://localhost:8000; do
          sleep 1
        done

    - name: Check logs for test results
      run: docker logs my-django-container | grep "Ran"
