name: Docker CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: actions/setup-python@v3
      with:
        python-version: 3.12

    - name: Build Docker image
      run: docker build -t my-django-app .

    - name: Run Docker container
      run: docker run -d -p 8000:8000 --name my-django-container my-django-app

    - name: Test
      run: docker exec my-django-container python manage.py test

